
#PRIVATES
RULE_TARGET_DIR := $(TARGET_DIR)\OS\arch\ok6410
RULE_SUB_SYSTEM := 
RULE_TARGET_DEPEND := built_in_func.o start.o low_level.o 
RULE_TARGET_DEPEND += arch_context.o arch_exception.o
RULE_TARGET_DEPEND += arch_tick.o gptimer.o
RULE_TARGET := _ok6410
include $(RULE_DIR)\rule.mk