
#PRIVATEs
RULE_TARGET_DIR := $(TARGET_DIR)\OS\kernel
RULE_SUB_SYSTEM := lib
RULE_TARGET_DEPEND := base_obj.o blockQ.o cpu.o tick.o interrupt.o ipi.o memory.o 
RULE_TARGET_DEPEND += pend_obj.o semaphore.o mutex.o msg_box.o thread.o rtbf_thread.o 
RULE_TARGET_DEPEND += rt_sched.o kernel.o osinit.o prioQ.o idle_thread.o error.o
RULE_TARGET := _kernel
include $(RULE_DIR)\rule.mk